- include_vars: 'vault.yml'

- name: apt packages
  apt:
    name: [
      'python-pip',
      'alsa-utils',
    ]
  become: yes

- shell: pip install docker
  args:
    creates: /usr/local/lib/python2.7/dist-packages/docker
  become: yes

- template:
    src: docker-compose.yml
    dest: docker-compose.yml

- template:
    src: shairport-sync.conf
    dest: shairport-sync.conf

- file:
    path: daapd
    state: directory

- copy:
    src: ~/home/daapd/Dockerfile
    dest: daapd/

- copy:
    src: ~/home/daapd/start.sh
    dest: daapd/

- copy:
    src: forked-daapd.conf
    dest: daapd/
