- include_vars: 'vault.yml'
  tags: copy

- shell: curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: apt packages
  apt: name={{ item }}
  with_items: ['{{apt_packages}}']
  become: yes

- name: npm packages
  npm: name={{ item }} global=yes
  with_items: ['{{npm_packages}}']
  become: yes

- file:
    path: /home/homeassistant/.homeassistant/custom_components/sensor/
    state: directory
    recurse: yes
    owner: homeassistant
  become: yes

- get_url:
    url: https://raw.githubusercontent.com/tchellomello/home-assistant/ring/homeassistant/components/sensor/ring.py
    dest: /home/homeassistant/.homeassistant/custom_components/sensor/ring.py
    owner: homeassistant
  become: yes

- name: zwave options
  template:
    src: options.xml
    dest: /srv/homeassistant/src/python-openzwave/openzwave/config/options.xml
  become: yes
  become_user: homeassistant

- template:
    src: '{{ item }}'
    dest: /home/homeassistant/.homeassistant/{{ item | basename }}
  with_fileglob:
    - ../templates/*.yaml
  become: yes
  become_user: homeassistant
  notify:
    - restart hass
  tags: copy

- file:
    path: /home/homeassistant/.homebridge
    state: directory
    owner: homeassistant
  become: yes

- copy:
    src: homebridge@homeassistant.service
    dest: /etc/systemd/system/homebridge@homeassistant.service
  become: yes
  notify:
    - restart homebridge

- template:
    src: config.json
    dest: /home/homeassistant/.homebridge/config.json
  become: yes
  become_user: homeassistant
  notify:
    - restart homebridge
