- include_vars: 'vault.yml'
  tags:
    - debug
    - copy

- name: apt packages
  apt: name={{ item }}
  with_items: ['{{apt_packages}}']
  become: yes

- template:
    src: monitrc
    dest: /etc/monit/monitrc
  become: yes

- copy:
    src: '{{ item }}'
    dest: /etc/monit/conf.d/{{ item | basename }}
  with_fileglob:
    - ../templates/monit/*
  become: yes

- copy:
    src: '{{ item }}'
    dest: /usr/local/bin/{{ item | basename }}
    mode: a+x
  with_fileglob:
    - ../files/bin/*
  become: yes
