- include_vars: 'vault.yml'
  tags:
    - debug
    - copy

- shell: pip install docker
  args:
    creates: /usr/local/lib/python2.7/dist-packages/docker
  become: yes
  tags: debug

- shell: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- shell: wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/stretch.list
  become: yes
  args:
    creates: /etc/apt/sources.list.d/mopidy.list

- name: apt packages
  apt: name={{ item }}
  with_items: ['{{apt_packages}}']
  become: yes

- name: pip packages
  pip: name={{ item }}
  with_items: ['{{pip_packages}}']
  become: yes

- file:
    path: .homeassistant
    state: directory

- file:
    path: .homeassistant/known_devices.yaml
    state: touch

- template:
    src: '{{ item }}'
    dest: .homeassistant/{{ item | basename }}
  with_fileglob:
    - ../templates/*.yaml
  notify:
    - restart hass
  tags: copy

- docker_container:
    name: home-assistant
    image: homeassistant/home-assistant:latest
    volumes:
      - "/home/tball/.homeassistant:/config"
      - /etc/localtime:/etc/localtime:ro
    restart_policy: unless-stopped
    network_mode: host
  become: yes

- template:
    src: mopidy.conf
    dest: /etc/mopidy/mopidy.conf
  become: yes
  tags: copy
  notify:
    - restart mopidy

- template:
    src: icecast.xml
    dest: /etc/icecast2/icecast.xml
  become: yes
  tags: copy
  notify:
    - restart icecast
