version: "3"

services:
  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    domainname: 2030davenport.com
    networks:
      - local
      - traefik_proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    env_file:
      - ./traefik.env
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:traefik.2030davenport.com
      - traefik.port=8080
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=2030davenport.com
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=true
    restart: always

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    depends_on:
      - traefik
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.backend=homeassistant
      - traefik.frontend.rule=Host:2030davenport.com
      - traefik.port=8123
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=2030davenport.com
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=true
    networks:
      - traefik_proxy
      - local
    ports:
      - 8123:8123
    environment:
      - TZ=America/Toronto
    restart: unless-stopped

  spotify:
    container_name: spotify
    restart: always
    build: librespot
    volumes:
      - /mnt/pool/tunes/spotify:/data
    env_file:
      - ./librespot.env

  shairport:
    container_name: shairport
    image: kevineye/shairport-sync
    network_mode: host
    volumes:
      - /mnt/pool/tunes/airplay:/output
      - /mnt/pool/tunes/airplay.metadata:/tmp/shairport-sync-metadata
    environment:
      - AIRPLAY_NAME=Home
    command: --metadata-pipename=/tmp/shairport-sync-metadata -o pipe -- /output


  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing
    volumes:
      - ./syncthing:/config
      - /mnt/pool:/mnt
    environment:
      - PGID=1000
      - PUID=1000
      - UMASK_SET=022
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  local:
    driver: bridge
