version: "3.5"

services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    ports:
      - 8123:8123
      - 51827:51827 # homekit
    environment:
      - TZ=America/Toronto
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always

  spotify:
    container_name: spotify
    restart: always
    build: librespot
    depends_on:
      - daapd
    volumes:
      - /mnt/pool/tunes/spotify:/data
    env_file:
      - ./librespot.env
    restart: always

  shairport:
    container_name: shairport
    image: kevineye/shairport-sync
    network_mode: host
    depends_on:
      - daapd
    volumes:
      - /mnt/pool/tunes/airplay:/output
      - /mnt/pool/tunes/airplay.metadata:/tmp/shairport-sync-metadata
    environment:
      - AIRPLAY_NAME=Home
    command: --metadata-pipename=/tmp/shairport-sync-metadata -o pipe -- /output
    restart: always

  daapd:
    container_name: daapd
    build: daapd
    network_mode: host
    volumes:
      - /mnt/pool/tunes:/mnt/pool/tunes:ro
      - ./daapd/forked-daapd.conf:/etc/forked-daapd.conf
    environment:
      - MEDIA_SERVER_NAME=Home
      - PUID=1000
    env_file:
      - ./daapd.env
    ports:
      - "6600:6600/tcp"
    restart: always

  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing
    network_mode: host
    volumes:
      - ./:/homebackup
      - ./syncthing:/config
      - /mnt/pool:/mnt
    environment:
      - PGID=1000
      - PUID=1000
      - UMASK_SET=022
    restart: always

  soulseek:
    container_name: soulseek
    image: danielguerra/soulseek
    volumes:
      - /mnt/pool/tunes:/home/soulseek/Music
      - /mnt/pool/downloads:/home/soulseek/Soulseek Downloads/complete
    ports:
      - 5900:5900
    restart: always

  subsonic:
    container_name: subsonic
    image: airsonicadvanced/airsonic-advanced:latest
    volumes:
      - /mnt/pool/tunes:/mnt/pool/tunes
      - ./subsonic:/var/airsonic
    environment:
      - TZ=America/Toronto
      - GID=1000
      - UID=1000
    network_mode: host
    restart: always

  weewx:
    container_name: weewx
    image: mitct02/weewx
    volumes:
      - ./weewx.conf:/home/weewx/archive
      - /mnt/pool/weather/archive:/home/weewx/archive
      - /mnt/pool/weather/www:/home/weewx/public_html

  weewx-web:
    container_name: weewx-web
    image: nginx
    volumes:
      - /mnt/pool/weather/www:/usr/share/nginx/html
    ports:
      - 8090:80
