version: "3"

services:
  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    domainname: 2030davenport.com
    network_mode: host
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      # - 3688:3688
    env_file:
      - ./traefik.env
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:traefik.2030davenport.com
      - traefik.port=8080
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=2030davenport.com
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=true
    restart: always

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    depends_on:
      - traefik
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    ports:
      - 8123:8123
      - 51827:51827 # homekit
    environment:
      - TZ=America/Toronto
    restart: always

  spotify:
    container_name: spotify
    restart: always
    build: librespot
    depends_on:
      - daapd
    volumes:
      - /mnt/pool/tunes/spotify:/data
    env_file:
      - ./librespot.env
    restart: always

  shairport:
    container_name: shairport
    image: kevineye/shairport-sync
    network_mode: host
    depends_on:
      - daapd
    volumes:
      - /mnt/pool/tunes/airplay:/output
      - /mnt/pool/tunes/airplay.metadata:/tmp/shairport-sync-metadata
    environment:
      - AIRPLAY_NAME=Home
    command: --metadata-pipename=/tmp/shairport-sync-metadata -o pipe -- /output
    restart: always

  daapd:
    container_name: daapd
    build: daapd
    network_mode: host
    volumes:
      - /mnt/pool/tunes:/mnt/pool/tunes:ro
      - ./daapd/forked-daapd.conf:/etc/forked-daapd.conf
    environment:
      - MEDIA_SERVER_NAME=Home
      - PUID=1000
    env_file:
      - ./daapd.env
    restart: always

  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing
    volumes:
      - ./:/homebackup
      - ./syncthing:/config
      - /mnt/pool:/mnt
    environment:
      - PGID=1000
      - PUID=1000
      - UMASK_SET=022
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: always

  soulseek:
    container_name: soulseek
    image: danielguerra/soulseek
    volumes:
      - /mnt/pool/tunes:/home/soulseek/Music
      - /mnt/pool/downloads:/home/soulseek/Soulseek Downloads/complete
    ports:
      - 5900:5900
    restart: always
