---
- hosts: hub
  roles:
    - hub

- hosts: speaker
  roles:
    - role: shairport-sync
      conf: |
        general = {
            name = "{{ ansible_hostname | regex_replace('\.local', '') }}";
          };
