---
- hosts: hub
  roles:
    - hub
  environment:
    PYTHONPATH: "{{ lookup('env','PYTHONPATH') }}:/usr/local/lib/python2.7/dist-packages"

- hosts: itunes
  roles:
    - itunes

- hosts: speaker
  roles:
    - role: shairport-sync
      conf: |
        general = {
            name = "%h";
          };
