---
- hosts: hub
  roles:
    - hub

- hosts: itunes
  roles:
    - itunes

- hosts: speaker
  roles:
    - role: shairport-sync
      conf: |
        general = {
            name = "%h";
          };
