- alias: Receiver Volume
  trigger:
    platform: state
    entity_id: input_number.receiver_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.receiver
      volume_level: '{{ states.input_number.receiver_volume.state | float }}'

- alias: Receiver Volume set
  trigger:
    platform: state
    entity_id: media_player.receiver
  action:
    - service: input_number.set_value
      data_template:
        entity_id: media_player.receiver
        value: "{{ state_attr('media_player.receiver', 'volume_level') | float }}"

- alias: Bedroom Volume
  trigger:
    platform: state
    entity_id: input_number.bedroom_volume
  action:
    service: rest_command.set_bedroom_volume

- alias: Bedroom Volume set
  trigger:
    platform: state
    entity_id: sensor.bedroom_volume
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.bedroom_volume
      value: '{{ trigger.to_state.state }}'

- alias: Bedroom Speaker On
  trigger:
    platform: state
    entity_id: sensor.bedroom_volume
  condition:
    - condition: template
      value_template: "{{ state_attr('sensor.bedroom_volume', 'selected') }}"
  action:
    - service: switch.turn_on
      entity_id: switch.bedroom_stereo

- alias: Bedroom Speaker Off
  trigger:
    platform: state
    entity_id: sensor.bedroom_volume
  condition:
    - condition: template
      value_template: "{{ state_attr('sensor.bedroom_volume', 'selected') == False }}"
  action:
    service: switch.turn_off
    entity_id: switch.bedroom_stereo

- alias: Office Volume
  trigger:
    platform: state
    entity_id: sensor.office_volume
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.office_volume
      value: '{{ trigger.to_state.state }}'

- alias: Office Volume set
  trigger:
    platform: state
    entity_id: input_number.office_volume
  action:
    service: rest_command.set_office_volume

- alias: Living Room Speaker On
  trigger:
    platform: state
    entity_id: sensor.living_room_volume
  condition:
    - condition: template
      value_template: "{{ state_attr('sensor.living_room_volume', 'selected') }}"
  action:
    - service: media_player.turn_on
      data:
        entity_id: media_player.receiver
    - service: media_player.select_source
      data:
        entity_id: media_player.receiver
        source: Stream
    - service: rest_command.set_living_room_volume

- alias: Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  action:
    service: scene.turn_on
    entity_id: scene.sunset

- alias: Good Night
  trigger:
    platform: time
    at: '01:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.good_night

- alias: Music Alarm
  trigger:
    platform: time
    minutes: '/1'
    seconds: '30'
  condition:
    - condition: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.music_alarm' , 'timestamp') | int | timestamp_custom('%H:%M', false)) }}"
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: state
      entity_id: device_tracker.tylers_phone
      state: 'home'
  action:
    service: script.music_alarm

- alias: Light alarm
  trigger:
    platform: time
    minutes: '/1'
    seconds: '30'
  condition:
    - condition: template
      value_template: '{{ states.sensor.time.state == (states.input_datetime.light_alarm.attributes.timestamp | int | timestamp_custom("%H:%M", False)) }}'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: state
      entity_id: device_tracker.jens_phone
      state: 'home'
  action:
    - service: script.light_alarm

- alias: Out late
  trigger:
    platform: state
    entity_id: device_tracker.tylers_phone, device_tracker.jens_phone
    from: 'home'
    to: 'not_home'
  condition:
    condition: time
    after: '01:00:00'
    before: '06:00:00'
  action:
    service: light.turn_on
    data:
      entity_id: light.porch_light
      brightness: 10

- alias: Return late
  trigger:
    platform: state
    entity_id: device_tracker.tylers_phone, device_tracker.jens_phone
    from: 'not_home'
    to: 'home'
  condition:
    condition: time
    after: '01:00:00'
    before: '06:00:00'
  action:
    - delay: 0:30
    - service: light.turn_off
      entity_id: light.porch_light

- alias: Sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: "-00:30:00"
  action:
    service: scene.turn_on
    entity_id: scene.good_night

- alias: Ecobee away
  trigger:
    platform: state
    entity_id: group.device_trackers
    from: 'home'
    to: 'not_home'
    for:
      hours: 1
      minutes: 0
  condition:
    - condition: template
      value_template: "{{ states('group.occupancy_sensors') == 'off' }}"
  action:
    service: climate.set_away_mode
    data:
      entity_id: climate.home
      away_mode: true

- alias: Ecobee home
  trigger:
    platform: state
    entity_id: group.device_trackers
    from: 'not_home'
    to: 'home'
    for:
      minutes: 20
  action:
    service: climate.set_away_mode
    data:
      entity_id: climate.home
      away_mode: false

- alias: Fetch discogs item
  trigger:
    platform: time
    minutes: '/15'
    seconds: '00'
  action:
    service: shell_command.discogs_random_release

- alias: Fetch discogs json
  trigger:
    platform: time
    minutes: '/15'
    seconds: '30'
  action:
    service: shell_command.discogs_random_json
