- alias: Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  action:
    service: scene.turn_on
    entity_id: scene.sunset

- alias: Good Night
  trigger:
    platform: time
    at: '01:00:00'
  condition:
    - condition: state
      entity_id: media_player.sony_bravia_tv
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.good_night

- alias: Music Alarm
  trigger:
    platform: time_pattern
    minutes: '/1'
    seconds: '30'
  condition:
    - condition: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.music_alarm' , 'timestamp') | int | timestamp_custom('%H:%M', false)) }}"
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: state
      entity_id: device_tracker.tylers_phone
      state: 'home'
  action:
    service: script.music_alarm

- alias: Light alarm
  trigger:
    platform: time_pattern
    minutes: '/1'
    seconds: '30'
  condition:
    - condition: template
      value_template: '{{ states.sensor.time.state == (states.input_datetime.light_alarm.attributes.timestamp | int | timestamp_custom("%H:%M", False)) }}'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: state
      entity_id: device_tracker.jens_phone
      state: 'home'
  action:
    - service: script.light_alarm

- alias: Sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: "-00:30:00"
  action:
    service: scene.turn_on
    entity_id: scene.good_night

- alias: Fetch discogs item
  trigger:
    platform: time_pattern
    minutes: '/15'
    seconds: '0'
  action:
    service: shell_command.discogs_random_release

- alias: Fetch discogs json
  trigger:
    platform: time_pattern
    minutes: '/15'
    seconds: '30'
  action:
    service: shell_command.discogs_random_json

- alias: fade bedroom light
  trigger:
    platform: state
    entity_id: light.tylers_light
    from: 'off'
    to: 'on'
  condition:
    - condition: sun
      after: sunset
  action:
    service: light.turn_on
    brightness: 80
