homeassistant:
  name: Davenport
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 101
  unit_system: metric
  time_zone: America/Toronto
  whitelist_external_dirs:
    - /config

  packages: !include_dir_named packages

default_config:

http:
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret host_ip
  trusted_networks:
    - 127.0.0.1
  ip_ban_enabled: true
  login_attempts_threshold: 5

frontend: !include frontend.yaml
lovelace:
  mode: yaml

folder_watcher:
  - folder: /config
    patterns:
      - '*.yaml'

discovery:
  ignore:
    - google_cast
  enable:
    - homekit
config:
sun:
ios:
homekit:
  filter:
    include_domains:
      - scene
      - script
      - media_player
      - cover.garage

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key

weather:
  - platform: darksky
    api_key: !secret darksky_key
    units: ca
    mode: daily

calendar:
  - platform: caldav
    username: !secret email
    password: !secret caldav_password
    url: !secret caldav_url
    calendars:
      - 'Jen/Tyler'

media_player:
  - platform: braviatv
    host: !secret bravia_ip

ecobee:
  api_key: !secret ecobee_api_key

stream:
camera:
  - platform: ring
  - platform: foscam
    ip: !secret rivercam_ip
    username: !secret rivercam_user
    password: !secret rivercam_pass

notify:
  - platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

ring:
  username: !secret email
  password: !secret ring_password

cover:
  - platform: myq
    username: !secret email
    password: !secret myq_password
    type: chamberlain

lutron_caseta:
  host: !secret caseta_ip
  keyfile: caseta.key
  certfile: caseta.crt
  ca_certs: caseta-bridge.crt

logger:
  default: warning
  logs:
    # homeassistant.components.tradfri: debug

device_tracker:
  - platform: unifi
    host: !secret unifi_ip
    port: 8443
    verify_ssl: false
    username: !secret unifi_username
    password: !secret unifi_password
    site_id: !secret unifi_site
    detection_time: 180
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false

shinobi:
  host: !secret shinobi_host
  api_key: !secret shinobi_key
  group_key: !secret shinobi_group

rest_command:
  river_record:
    url: !secret rivercam_url_rec
  river_stop:
    url: !secret rivercam_url_stop

speedtestdotnet:
  scan_interval: '05:00'
  monitored_conditions:
    - ping
    - download
    - upload

input_datetime:
  music_alarm:
    name: Music Wake Up
    has_date: false
    has_time: true
    initial: '08:15'
  light_alarm:
    name: Light alarm
    has_date: false
    has_time: true
    initial: '06:00'

scene: !include scenes.yaml
script: !include script.yaml
automation: !include automation.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensors.yaml
shell_command: !include shell_commands.yaml
group: !include groups.yaml
