homeassistant:
  name: Davenport
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 101
  unit_system: metric
  time_zone: America/Toronto
  whitelist_external_dirs:
    - /config

http:
  api_password: !secret api_password
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret host_ip
  ip_ban_enabled: true
  login_attempts_threshold: 5

frontend: !include frontend.yaml
lovelace:
  mode: yaml

folder_watcher:
  - folder: /config
    patterns:
      - '*.yaml'

discovery:
  ignore:
    - google_cast
  enable:
    - homekit
config:
logbook:
history:
sun:
ios:
weather:
  - platform: darksky
    api_key: !secret darksky_key
    units: ca

calendar:
  - platform: caldav
    username: !secret email
    password: !secret caldav_password
    url: !secret caldav_url

media_player:
  - platform: onkyo
    host: !secret receiver_ip
    name: receiver
    sources:
      video2_cbl_sat: 'Turntables'
      cd_tv/cd: 'Apple TV'
      network: 'Spotify'
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
    aliases:
      70f8bb9a8a5393ef080507a89e4b98d139000d65: home
      126a80ef484035c196dd9f39d0c1a2c9e869810c: receiver
      009e058c883c683e1330228851ecafe3265c8f51: bedroom
  - platform: braviatv
    host: !secret bravia_ip
  - platform: mpd
    host: !secret host_ip

ecobee:
  api_key: !secret ecobee_api_key

camera:
  - platform: foscam
    ip: !secret foscam_ip
    username: tylerball
    password: !secret foscam_password
  - platform: ring

notify:
  - platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

ring:
  username: !secret email
  password: !secret ring_password

cover:
  - platform: myq
    username: !secret email
    password: !secret myq_password
    type: chamberlain

lutron_caseta:
  host: !secret caseta_ip
  keyfile: caseta.key
  certfile: caseta.crt
  ca_certs: caseta-bridge.crt

logger:
  default: warning
  logs:
    homeassistant.components.media_player.spotify: debug
    homeassistant.components.tradfri: debug
    homeassistant.components.calendar: debug
    homeassistant.components.unifi: debug
    homeassistant.components.switch.unifi: debug

device_tracker:
  - platform: unifi
    host: !secret unifi_ip
    port: 8443
    verify_ssl: false
    username: !secret unifi_username
    password: !secret unifi_password
    site_id: !secret unifi_site
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false

input_datetime:
  alarm:
    name: Music Wake Up
    has_date: false
    has_time: true
    initial: '08:15'

scene: !include scenes.yaml
script: !include script.yaml
automation: !include automation.yaml
# group: !include groups.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml
input_number: !include input_number.yaml
rest_command: !include rest_command.yaml
