- platform: time_date
- platform: yr
- platform: ring
  username: !secret email
  password: !secret ring_password
  monitored_conditions:
    - battery
    - last_activity
    - last_ding
    - last_motion
    - volume

- platform: transmission
  host: !secret transmission_ip
  username: admin
  password: !secret transmission_password
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'

- platform: discogs
  token: !secret discogs_token

- platform: file
  name: Discogs Item Image
  file_path: /config/discogs.json
  value_template: '{{ value_json.images[0].uri }}'

- platform: file
  name: Discogs Item Desc
  file_path: /config/discogs.json
  value_template: '{{ value_json.artists[0].name }} — {{ value_json.title }}'

- platform: google_travel_time
  api_key: !secret google_api_key
  origin: zone.home
  destination: !secret address_tyler_work
  name: Travel Time Tyler
  options:
    mode: transit

- platform: google_travel_time
  api_key: !secret google_api_key
  origin: zone.home
  destination: !secret address_jen_work
  name: Travel Time Jen
  options:
    mode: transit

- platform: ttc
  route: 168
  tag: 2540

- platform: ttc
  route: 127
  tag: 2540

- platform: speedtest
  hour: 5
  minute: 0
  monitored_conditions:
    - ping
    - download
    - upload
