- platform: time_date
- platform: yr
- platform: discogs
  token: !secret discogs_token

- platform: file
  name: Discogs Item Image
  file_path: /config/discogs.json
  value_template: '{{ value_json.images[0].uri }}'

- platform: file
  name: Discogs Item Desc
  file_path: /config/discogs.json
  value_template: '{{ value_json.artists[0].name }} — {{ value_json.title }}'

- platform: google_travel_time
  api_key: !secret google_api_key
  origin: zone.home
  destination: !secret address_tyler_work
  name: Travel Time Tyler
  options:
    mode: transit

- platform: google_travel_time
  api_key: !secret google_api_key
  origin: zone.home
  destination: !secret address_jen_work
  name: Travel Time Jen
  options:
    mode: transit

- platform: nextbus
  agency: ttc
  route: 168
  stop: 2540

- platform: nextbus
  agency: ttc
  route: 127
  stop: 2540

# - platform: wunderground
#   api_key: !secret wunderground_key
#   monitored_conditions:
#     - temp_high_record_c
#     - temp_high_1d_c
#     - temp_c
#     - temp_low_1d_c
#     - temp_low_record_c
#     - precip_1d
#     - precip_1d_mm
#     - wind_kph
#     - wind_1d_kph
#     - alerts
