resources:
  - url: /local/discogs-card.js
    type: js
  - url: /local/group-card.js
    type: js
  - url: /local/ttc.js
    type: js
  - url: /local/forked-daapd-card/forked-daapd-card.js?v=0.0.2
    type: module
  - url: /local/mini-media-player-bundle.js?v=1.9.1
    type: module
title: Davenport
views:
  - id: travel
    title: travel
    icon: mdi:pin
    cards:
      - type: 'custom:ttc-card'
        entity: sensor.ttc_168

      - type: 'custom:ttc-card'
        entity: sensor.ttc_127

      - type: 'custom:discogs-card'
