title: Davenport
views:
  - id: home
    title: home
    icon: mdi:home
    cards:
      - type: conditional
        conditions:
          - entity: cover.garage
            state: "closed"
        card:
          type: entity-button
          name: Garage Door
          entity: cover.garage
          icon: mdi:format-vertical-align-top
          tap_action:
            action: call-service
            service: cover.open_cover
            service_data:
              entity_id: cover.garage
      - type: conditional
        conditions:
          - entity: cover.garage
            state: "open"
        card:
          type: entity-button
          name: Garage Door
          entity: cover.garage
          icon: mdi:format-vertical-align-bottom
          tap_action:
            action: call-service
            service: cover.close_cover
            service_data:
              entity_id: cover.garage

      - type: vertical-stack
        cards:
        - type: iframe
          url: https://embed.windy.com/embed2.html?lat=42.310&lon=-79.453&zoom=6&level=surface&overlay=wind&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=43.689&detailLon=-79.451&metricWind=default&metricTemp=default&radarRange=-1
          title: Weather radar
        - type: weather-forecast
          entity: weather.dark_sky

      - type: vertical-stack
        cards:
        - type: thermostat
          entity: climate.home
        - type: sensor
          entity: sensor.home_temperature
          name: Home Temperature
          graph: line

      - type: picture-entity
        entity: camera.front_door
        name: Front Door
      - type: conditional
        conditions:
          - entity: device_tracker.tylers_phone, device_tracker.jens_phone
            state: 'not_home'
        card:
          type: picture-entity
          entity: camera.foscam_camera
          name: RiverCam

  - id: alarms
    title: alarms
    icon: mdi:alarm
    cards:
      - card:
        type: entities
        show_header_toggle: false
        entities:
          - entity: input_datetime.music_alarm
          - entity: automation.music_alarm

      - card:
        type: entities
        show_header_toggle: false
        entities:
          - entity: input_datetime.light_alarm
          - entity: automation.light_alarm


  - id: media
    title: media
    icon: mdi:speaker
    cards:
      - type: conditional
        conditions:
          - entity: media_player.spotify
            state: "playing"
        card:
          type: media-control
          entity: media_player.spotify
      - type: conditional
        conditions:
          - entity: media_player.spotify
            state_not: "playing"
        card:
          type: media-control
          entity: media_player.mpd

      - card:
        type: entities
        title: Speakers
        show_header_toggle: false
        column_width: 50%
        entities:
          - entity: switch.living_room_speakers
            name: Living Room
            tap_action: toggle
          - entity: input_number.receiver_volume
            name: Living Room Volume

          - entity: switch.bedroom_speakers
            name: Bedroom
            icon: mdi:airplay
            tap_action: toggle
          - entity: input_number.bedroom_volume
            name: Bedroom Volume

          - entity: switch.office_speakers
            name: Office
            tap_action: toggle
          - entity: input_number.office_volume
            name: Office Volume

          - entity: switch.kitchen_speakers
            name: Kitchen
            tap_action: toggle

  - id: library
    title: library
    icon: mdi:music
    panel: true
    cards:
      - type: iframe
        url: http://192.168.1.50:3689

