resources:
  - url: /local/discogs-card.js
    type: js
  - url: /local/group-card.js
    type: js
  - url: /local/ttc.js
    type: js
title: Davenport
views:
  - id: travel
    title: travel
    icon: mdi:pin
    cards:
      - type: entities
        entities:
          - type: entity-button
            name: Front Door
            entity: lock.front_door
          - type: entity-button
            name: Garage Door
            entity: cover.garage
          - entity: sensor.travel_time_tyler
            name: Travel Time to Tyler's Work
          - entity: sensor.travel_time_jen
            name: Travel Time to Jen's Work

      - type: 'custom:ttc-card'
        entity: sensor.ttc_168

      - type: 'custom:ttc-card'
        entity: sensor.ttc_127

      - type: weather-forecast
        entity: weather.dark_sky
      - type: iframe
        url: /local/darksky-map.html
        aspect_ratio: 60%

  - id: home
    title: home
    icon: mdi:home
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - scene.sunset
          - scene.good_night

      - type: thermostat
        entity: climate.home

      - type: custom:group-card
        card:
          type: entities
          title: Bedroom lights
        group: group.bedroom_lights

      - type: custom:group-card
        card:
          type: entities
          title: Living room lights
        group: group.living_room_lights

      - type: custom:group-card
        card:
          type: entities
          title: Entrance lights
        group: group.entrance_lights

      - type: custom:group-card
        card:
          type: entities
          title: Basement lights
        group: group.basement_lights

      - type: picture-entity
        entity: camera.front_door
        name: Front Door

      - type: conditional
        conditions:
          - entity: group.device_trackers
            state: 'not_home'
        card:
          type: picture-entity
          entity: camera.rivercam
          name: RiverCam

      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
          - type: sensor
            entity: sensor.home_temperature
            name: living room
            graph: line
          - type: sensor
            entity: sensor.kitchen_temperature
            name: kitchen
            graph: line

        - type: horizontal-stack
          cards:
          - type: sensor
            entity: sensor.bedroom_temperature
            name: Bedroom
            graph: line
          - type: sensor
            entity: sensor.office_temperature
            name: Office
            graph: line

  - id: alarms
    title: alarms
    icon: mdi:alarm
    cards:
      - card:
        type: entities
        show_header_toggle: false
        entities:
          - entity: input_datetime.music_alarm
          - entity: automation.music_alarm

      - card:
        type: entities
        show_header_toggle: false
        entities:
          - entity: input_datetime.light_alarm
          - entity: automation.light_alarm

  - id: media
    title: media
    icon: mdi:speaker
    cards:
      - type: conditional
        conditions:
          - entity: media_player.spotify
            state: "playing"
        card:
          type: media-control
          entity: media_player.spotify
      - type: conditional
        conditions:
          - entity: media_player.spotify
            state_not: "playing"
        card:
          type: media-control
          entity: media_player.mpd

      - card:
        type: entities
        title: Speakers
        show_header_toggle: false
        column_width: 50%
        entities:
          - entity: switch.living_room_speakers
            name: Living Room
            tap_action: toggle
          - entity: input_number.receiver_volume
            name: Living Room Volume

          - entity: switch.bedroom_speakers
            name: Bedroom
            icon: mdi:airplay
            tap_action: toggle
          - entity: input_number.bedroom_volume
            name: Bedroom Volume

          - entity: switch.office_speakers
            name: Office
            tap_action: toggle
          - entity: input_number.office_volume
            name: Office Volume

          - entity: switch.kitchen_speakers
            name: Kitchen
            tap_action: toggle
          - entity: input_number.kitchen_volume
            name: Kitchen Volume

          - entity: switch.garage_speakers
            name: Garage
            tap_action: toggle
          - entity: input_number.garage_volume
            name: Garage Volume

      - type: 'custom:discogs-card'

  - id: library
    title: library
    icon: mdi:music
    panel: true
    cards:
      - type: iframe
        url: http://192.168.1.50:3689

  - id: charts
    title: charts
    icon: mdi:chart-line
    cards:
      - type: sensor
        entity: sensor.speedtest_download
        name: Internet Download
        graph: line
      - type: sensor
        entity: sensor.speedtest_upload
        name: Internet Upload
        graph: line
      - type: sensor
        entity: sensor.speedtest_ping
        name: Internet Ping
        graph: line
