[frontends]
  [frontends.frontend-daapd]
  backend = "backend-daapd"
  passHostHeader = true
  InsecureSkipVerify = true
  [frontends.frontend-daapd.routes]
  [frontends.frontend-daapd.routes.route-daapd-ext]
  rule = "Host:daapd.2030davenport.com"

[backends]
  [backends.backend-daapd]
  [backends.backend-daapd.servers]
  [backends.backend-daapd.servers.server-daapd-ext]
  url = "http://192.168.1.50:3689"
  weight = 0
