InsecureSkipVerify = true
defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  # [entryPoints.ws]
  # address = ":3688"
  #   [entryPoints.ws.tls]

[acme]
email = "tyler@tylerball.net"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
acmeLogging=true
onDemand = false
[acme.dnsChallenge]
  provider = "linode"
  delayBeforeCheck = 0
[[acme.domains]]
  main = "2030davenport.com"
[[acme.domains]]
  main = "*.2030davenport.com"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "2030davenport.com"
exposedByDefault = false
watch = true

[api]
  entryPoint = "traefik"
  dashboard = true
  address = ":8080"

[accessLog]
  filePath = "/etc/traefik/access.log"

[file]
  filename = "/etc/traefik/rules.toml"
  watch = true
