defaultEntryPoints = ["https", "http"]

[log]
level = "DEBUG"

[entryPoints]
  [entryPoints.https]
  address = ":443"
  [entryPoints.http]
  address = ":80"
  [entryPoints.ws]
  address = ":3687"

[serversTransport]
  insecureSkipVerify = true

[certificatesResolvers.linode.acme]
email = "tyler@tylerball.net"
storage = "/etc/traefik/acme/acme.json"
[certificatesResolvers.linode.acme.dnsChallenge]
  provider = "linode"
  delayBeforeCheck = 0
[[certificateResolvers.davenport.acme.domains]]
  main = "2030davenport.com"
[[certificateResolvers.davenport.acme.domains]]
  main = "*.2030davenport.com"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "2030davenport.com"
exposedByDefault = false
watch = true

[api]
  dashboard = true

[accessLog]
  filePath = "/etc/traefik/access.log"

[providers]
  [providers.file]
    filename = "/etc/traefik/rules.toml"
    watch = true
