alias: Receiver Volume
trigger:
  platform: state
  entity_id: input_slider.receiver_volume
action:
  - service: media_player.turn_on
    entity_id: media_player.receiver
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.receiver
      volume_level: {% raw %}'{{ trigger.to_state.state | float }}'{% endraw %}

trigger:
  platform: time
  at: '08:10:00'
action:
  service: script.music_alarm
