homeassistant:
  name: Davenport
  latitude: {{ hass.latitude }}
  longitude: {{ hass.longitude }}
  elevation: 101
  unit_system: metric
  time_zone: America/Toronto

http:
  api_password: '{{ hass.api_password }}'
  base_url: https://{{ url }}
  use_x_forwarded_for: true
  trusted_proxies:
    - {{ host_ip }}
  ip_ban_enabled: true
  login_attempts_threshold: 5

frontend: !include frontend.yaml
lovelace:
  mode: yaml

folder_watcher:
  - folder: /config
    patterns:
      - '*.yaml'

discovery:
  ignore:
    - google_cast
  enable:
    - homekit
config:
logbook:
history:
sun:
ios:
weather:
  - platform: darksky
    api_key: {{ darksky_key }}
    units: ca

calendar:
  - platform: caldav
    username: {{ email }}
    password: {{ caldav_pass }}
    url: {{ caldav_url }}

media_player:
  - platform: onkyo
    host: {{ receiver_ip }}
    name: receiver
    sources:
      tv-cd: 'Apple TV'
      network: 'Spotify'
  # - platform: mpd
  #   host: 192.168.1.50
  # - platform: snapcast
  #   host: 192.168.1.50
  - platform: spotify
    client_id: {{ hass.spotify_client }}
    client_secret: {{ hass.spotify_secret }}
    aliases:
      126a80ef484035c196dd9f39d0c1a2c9e869810c: receiver
      009e058c883c683e1330228851ecafe3265c8f51: bedroom
  - platform: braviatv
    host: {{ tv_ip }}

ecobee:
  api_key: {{ hass.ecobee_key }}

camera:
  - platform: foscam
    ip: {{ foscam_ip }}
    username: tylerball
    password: {{ hass.foscam_password }}
  - platform: ring

input_number:
  receiver_volume:
    name: Receiver
    initial: 0.25
    min: 0
    max: 1
    step: 0.05

notify:
  - platform: pushover
    api_key: {{ hass.pushover_api_key }}
    user_key: {{ hass.pushover_user_key }}

ring:
  username: {{ hass.ring_username }}
  password: {{ hass.ring_password }}

cover:
  - platform: myq
    username: {{ myq.user }}
    password: {{ myq.pass }}
    type: chamberlain

tradfri:

script: !include script.yaml
automation: !include automation.yaml
# group: !include groups.yaml
sensor: !include sensor.yaml
