version: "3"

services:
  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    domainname: {{ url }}
    networks:
      - local
      - traefik_proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - "LINODE_API_KEY={{ linode_api_key }}"
      - TZ=America/Toronto
    volumes:
      - "/home/tball/traefik:/etc/traefik"
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:traefik.{{ url }}
      - traefik.port=8080
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost={{ url }}
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=true
    restart: always
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    depends_on:
      - traefik
    volumes:
      - "/home/tball/.homeassistant:/config"
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.backend=homeassistant
      - traefik.frontend.rule=Host:{{ url }}
      - traefik.port=8123
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost={{ url }}
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=true
    networks:
      - traefik_proxy
      - local
    ports:
      - 8123:8123
    environment:
      - TZ=America/Toronto
    restart: unless-stopped
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  local:
    driver: bridge
