apple_tv_on:
  alias: 'Apple TV'
  sequence:
    - service: media_player.turn_on
      data:
        entity_id: media_player.receiver
    - service: media_player.select_source
      data:
        entity_id: media_player.receiver
        source: 'pc'
