- include_vars: 'vault.yml'

- name: apt packages
  apt: name={{ item }}
  with_items: ['{{apt_packages}}']
  become: yes

- git:
    repo: https://github.com/ejurgensen/forked-daapd.git
    dest: /home/pi/forked-daapd

- group:
    name: daapd
  become: yes

- user:
    name: daapd
    groups: daapd
  become: yes

- copy:
    src: forked-daapd.conf
    dest: /etc/forked-daapd.conf
  become: yes
  notify:
    - restart forked-daapd

- copy:
    src: forked-daapd.service
    dest: /etc/systemd/system/forked-daapd.service
  become: yes
  notify:
    - restart forked-daapd

- cron:
    minute: "0"
    hour: "4"
    job: "rsync -avzLP -e ssh --delete --chown=pi:daapd --no-perms --exclude='.git' --exclude='beets.db' tball@192.168.1.7:/mnt/tunes/ /mnt/music"
    user: pi
