media_player:
  - platform: onkyo
    host: !secret receiver_ip
    name: receiver
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
    aliases:
      70f8bb9a8a5393ef080507a89e4b98d139000d65: home
      126a80ef484035c196dd9f39d0c1a2c9e869810c: receiver
      009e058c883c683e1330228851ecafe3265c8f51: bedroom
  - platform: mpd
    host: !secret host_ip

automation:
- alias: Receiver Volume
  trigger:
    platform: state
    entity_id: input_number.receiver_volume
  condition:
    condition: template
    value_template: "{{ state_attr('media_player.receiver', 'source') == 'Video 6' }}"
  action:
    - service: rest_command.set_living_room_volume
      data_template:
        volume: '{{ states.input_number.receiver_volume.state | float * 1.25 / 100 }}'
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.receiver
        volume_level: '{{ states.input_number.receiver_volume.state | float * 1.25 / 100 }}'

- alias: Receiver Volume set
  trigger:
    platform: state
    entity_id: media_player.receiver
  condition:
    condition: template
    value_template: "{{ state_attr('media_player.receiver', 'source') == 'Video 6' }}"
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.receiver_volume
        value: "{{ state_attr('media_player.receiver', 'volume_level') | float / 0.0125 }}"
    - service: rest_command.set_living_room_volume
      data_template:
        volume: '{{ state_attr("media_player.receiver", "volume_level") * 100 | int }}'

- alias: Receiver input change
  trigger:
    platform: state
    entity_id: media_player.receiver
  condition:
    condition: template
    value_template: "{{ state_attr('media_player.receiver', 'source') != 'Video 6' }}"
  action:
    - service: rest_command.unset_living_room
    - service: input_number.set_value
      data_template:
        entity_id: media_player.receiver
        value: "{{ state_attr('media_player.receiver', 'volume_level') | float / 0.0125 }}"

- alias: Living Room Speaker On
  trigger:
    platform: state
    entity_id: sensor.living_room_volume
  condition:
    - condition: template
      value_template: "{{ state_attr('sensor.living_room_volume', 'selected') }}"
  action:
    service: script.receiver_stream

script:
  volume_fade:
    alias: increase volume
    sequence:
    - service: rest_command.set_bedroom_volume
      data_template:
        volume: '{{ state_attr("sensor.bedroom_volume", "volume") +1 }}'
    - delay: 00:00:20
    - condition: template
      value_template: '{{ state_attr("sensor.bedroom_volume", "volume") < 20 }}'
    - service: script.volume_fade_b

  volume_fade_b:
    alias: increase volume
    sequence:
    - service: rest_command.set_bedroom_volume
      data_template:
        volume: '{{ state_attr("sensor.bedroom_volume", "volume") +1 }}'
    - delay: 00:00:20
    - condition: template
      value_template: '{{ state_attr("sensor.bedroom_volume", "volume") < 20 }}'
    - service: script.volume_fade

  receiver_stream:
    alias: 'receiver stream'
    sequence:
      - service: media_player.select_source
        data:
          entity_id: media_player.receiver
          source: 'video6'

sensor:
- platform: rest
  name: Bedroom Volume
  resource: !secret bedroom_speaker_url
  method: GET
  json_attributes: ["id","name","selected","volume"]
  value_template: "{{ value_json.volume }}"
  scan_interval: 10

- platform: rest
  name: Living Room Volume
  resource: !secret living_room_speaker_url
  method: GET
  json_attributes: ["id","name","selected","volume"]
  value_template: "{{ value_json.volume }}"
  scan_interval: 10

rest_command:
  set_bedroom_only:
    url: !secret output_set_url
    method: PUT
    payload: '{"outputs": ["57717329783414"] }'
  set_bedroom_volume:
    url: !secret bedroom_speaker_url
    method: PUT
    payload: '{"volume": {{ volume }}, "selected": true }'
  set_living_room_volume:
    url: !secret living_room_speaker_url
    method: PUT
    payload: '{"volume": {{ volume }}, "selected": true }'
  unset_living_room:
    url: !secret living_room_speaker_url
    method: PUT
    payload: '{"selected" : false }'

input_number:
  receiver_volume:
    name: Receiver
    min: 0
    max: 80
    step: 1
